# WORKSHOP DATA SCIENCE - DIA 1

Este notebook é uma versão interativa do conteúdo apresentado no primeiro dia do workshop.

---

## TÓPICOS ABORDADOS
* Contextualização
* Introdução à Ciência de Dados
* Introdução ao Google Colab e Jupyter
* Introdução à biblioteca Pandas

---

## 1. CONTEXTUALIZAÇÃO

### O QUE É CIÊNCIA DE DADOS?
A Ciência de Dados é a área que usa dados para gerar conhecimento e apoiar decisões. Ela combina negócios, tecnologia e estatística para entender o que aconteceu, por que aconteceu e o que pode acontecer no futuro.

O campo abrange diversas funções como Analista, Engenheiro e Cientista de Dados, que têm objetivos e responsabilidades distintos.

### Funções em Ciência de Dados

#### Analista de Dados (Foco em BI e Relatórios)
* Atua em limpeza, organização e visualização de dados.
* Foco em relatórios, dashboards e Business Intelligence (BI).
* **Habilidades:** Estatística descritiva, Storytelling, SQL, bancos relacionais e não relacionais.
* **Ferramentas:** Power BI, Google Data Studio, Python, R.

#### Engenheiro de Dados (Foco em Infraestrutura e Fluxo de Dados)
* Cria e mantém pipelines ETL/ELT e infraestruturas de dados.
* Entrega dados limpos a Analistas e Cientistas de Dados.
* Trabalha com Data Warehouses, Data Lakes e arquitetura orientada a eventos.
* **Linguagens:** Scala, Java, Python.

#### Cientista de Dados (Foco em Pesquisa e Machine Learning)
* Aplica metodologia científica, estatística inferencial e Machine Learning (ML).
* Testa hipóteses, cria modelos preditivos e gera insights.
* Trabalha com dados complexos vindos de Data Lakes.
* **Ferramentas:** Scikit-learn, TensorFlow, PyTorch.

### Ciclo de Atividades do Cientista de Dados
O processo de Ciência de Dados é um ciclo iterativo:

1.  **Ingestão de Dados**: Coleta de dados estruturados e não estruturados (manualmente, via web scraping ou dados em tempo real).
2.  **Armazenamento e Processamento**: Armazenamento em data warehouses ou data lakes. Preparação dos dados com limpeza, transformação e integração (ETL).
3.  **Análise de Dados**: Análise exploratória para entender padrões e gerar hipóteses. Uso de ferramentas e algoritmos para análises preditivas e aprendizado de máquina.
4.  **Comunicação (Apresentar Insights)**: Visualização de dados e storytelling para os stakeholders. Utilização de relatórios, gráficos e dashboards (com R e Python).

---

## 2. INTRODUÇÃO AO GOOGLE COLAB E JUPYTER

* **Jupyter Notebook**: É como um caderno digital interativo, onde é possível escrever e executar código, criar gráficos e adicionar explicações em texto no mesmo documento.
* **Google Colab**: É uma plataforma online baseada no Jupyter Notebook que permite criar e executar notebooks no navegador, sem necessidade de instalação. Em resumo: Jupyter é a versão local, Colab é a versão na nuvem.

### Células no Colab
Um notebook é construído a partir de células de dois tipos:

* **Células de Código (.py)**: Destinadas à escrita e execução de código Python.
* **Células de Texto (.md)**: Usadas para adicionar explicações, títulos e formatação de texto, usando a linguagem Markdown.

Essa combinação de código e texto torna o notebook uma ferramenta poderosa para análise exploratória e comunicação científica.

### Células de Código
* Cada célula pode ser executada separadamente clicando no botão "play" (▶) ou usando o atalho **Shift + Enter**.
* O resultado (saída, erro, gráfico) aparece logo abaixo da célula.
* **Estado Compartilhado**: Variáveis, funções ou DataFrames criados em uma célula executada ficam disponíveis para outras células no mesmo ambiente.

### Células de Texto (Markdown)
* Permite adicionar texto para explicar o código e a análise.
* Usos principais:
    * Criar títulos e seções (`#`, `##`, etc.).
    * Escrever explicações.
    * Aplicar formatações:
        * Negrito: `**texto**`
        * Itálico: `*texto*`
        * Código Inline: \`texto\`

### Instalação e Importação de Bibliotecas

Para instalar pacotes no Colab, usamos `!pip install`.

In [ ]:
# Exemplo de instalação de bibliotecas
!pip install pandas numpy matplotlib seaborn scikit-learn

Após a instalação, podemos importá-las.

In [ ]:
# Exemplo de importação de bibliotecas
import pandas as pd  # pd é o alias padrão para Pandas
import numpy as np   # np é o alias padrão para NumPy

### ✍️ Exercícios - Google Colab

**Exercício 1.1:** Crie uma célula de texto (clicando em "+ Texto") e escreva algo nela.

**Exercício 1.2:** Crie uma célula de código (clicando em "+ Código") e insira nela o comando `print("Hello, World!")`.

**Exercício 1.3:** Execute a célula de código (pressionando Shift + Enter).

**Workshop Ciência de Dados**

In [ ]:
print("Hello World")

---

## 3. INTRODUÇÃO À BIBLIOTECA PANDAS

* **Pandas** é uma biblioteca Python de código aberto usada para manipulação e análise de dados.
* Ela oferece estruturas de dados rápidas e flexíveis, ideais para trabalhar com dados tabulares.
* Em ciência de dados, o Pandas é essencial para limpar, transformar, organizar e analisar informações.

### Estruturas de Dados do Pandas

* **Series**: Um array unidimensional, como uma única coluna em uma tabela.
* **DataFrame**: Uma estrutura bidimensional, semelhante a uma planilha ou tabela de banco de dados. É a estrutura mais utilizada no Pandas.

### Datasets (Conjuntos de Dados)
* Um dataset é uma coleção de informações organizada em formato de tabela (linhas e colunas).
* São geralmente armazenados em formatos como CSV, TXT ou Excel.
* Nos Notebooks, esses dados são carregados em **DataFrames** para análise.

---

## 4. IMPORTANDO DATASETS

O primeiro passo é carregar os dados para um DataFrame. O Pandas oferece funções como `read_csv`, `read_excel`, etc..

### Montando o Google Drive

Para acessar arquivos do seu Google Drive, precisamos "montá-lo".

In [ ]:
# Exemplo de como montar o Google Drive
from google.colab import drive  # Importar a funcionalidade
import os  # Para verificar se arquivos existem

# Montar o Google Drive no diretório /content/drive
# Será solicitada autorização na primeira vez.
drive.mount('/content/drive')

### Lendo um Arquivo CSV

Após montar o Drive, definimos o caminho para o arquivo e usamos o `pd.read_csv()`.

In [ ]:
# --- CÉLULA DE SETUP ---
# Vamos importar o pandas e então importar o dataframe 'spotify_processed.csv'

import pandas as pd

# Dados de exemplo baseados no slide 33
caminho = '/content/drive/MyDrive/2025/Workshops/Ciência de Dados/Dia 01/Dia 01 - Ciência de Dados/spotify_processed.csv'
df_spotify = pd.read_csv(caminho)

print("DataFrame 'df_spotify' criado com sucesso!")

In [ ]:
# Para este notebook, vamos usar o df_spotify importado acima.
print("\nPrimeiras 5 linhas do DataFrame df_spotify:")
display(df_spotify.head()) # display() é melhor que print() para DataFrames no Colab

### ✍️ Exercícios - Importando Datasets

**Exercício 2.1:** Acesse "https://dontpad.com/dspet" e baixe o arquivo `.csv` disponibilizado.

**Exercício 2.2:** Faça upload do arquivo para seu Google Drive.

**Exercício 2.3:** Realize a montagem do Google Drive e importação do Pandas no Google Colab.

**Exercício 2.4:** No ícone de pasta (barra lateral esquerda), encontre o arquivo `spotify_processed.csv` e, com o botão direito, copie seu caminho.

**Exercício 2.5:** Atribua o caminho a uma variável `caminho` e leia o arquivo usando `pd.read_csv(caminho)`.

> **Dica:** Lembre-se de importar o `drive` de `google.colab` e usar `drive.mount('/content/drive')`. Para ler o arquivo, use `pd.read_csv(sua_variavel_caminho)`.

<details>
<summary>Clique aqui para ver a solução</summary>

```python
# Solução 2.3, 2.4 e 2.5
from google.colab import drive
import pandas as pd

# Monta o Google Drive
drive.mount('/content/drive')

# 2.4 e 2.5: Cole o caminho copiado do seu Google Drive
caminho = '/content/drive/MyDrive/spotify_processed.csv' # <-- COLE SEU CAMINHO AQUI
df_spotify = pd.read_csv(caminho)

print("DataFrame carregado com sucesso!")
display(df_spotify.head())

---

## 5. ESTRUTURA E MÉTRICAS

Funções para visualizar a estrutura e características do DataFrame:

* `.head()`: Mostra as 5 (ou x) primeiras linhas.
* `.tail()`: Mostra as 5 (ou x) últimas linhas.
* `.shape`: Retorna uma tupla (linhas, colunas).
* `.info()`: Exibe tipos de dados, valores não nulos e uso de memória.
* `.describe()`: Gera estatísticas descritivas (média, desvio, min, max, quartis).

In [ ]:
# Exemplo .head()
# Mostrar as primeiras 5 linhas
print("\nPrimeiras 5 linhas (.head()):")
display(df_spotify.head())

In [ ]:
# Exemplo .tail()
# Últimas 4 linhas
print("\nÚltimas 4 linhas (.tail(4)):")
display(df_spotify.tail(4))

In [ ]:
# Exemplo .shape
# Dimensões
print(f"\nDimensões (linhas, colunas): {df_spotify.shape}")

In [ ]:
# Exemplo .info()
# Informações Gerais (.info())
# .info() imprime diretamente, não precisa de display() ou print()
print("\nInformações Gerais (.info()):")
df_spotify.info()

In [ ]:
# Exemplo .describe()
# Estatísticas Descritivas (.describe())
# Apenas para colunas numéricas como 'duration_ms'
print("\nEstatísticas Descritivas (.describe()):")
display(df_spotify.describe())

### Métricas e Valores Específicos
Podemos obter informações mais específicas sobre os dados:

* `.nunique()`: Quantos itens únicos existem em uma coluna.
* `.unique()`: Quais são esses itens únicos.
* `.max()` / `.min()`: O maior e o menor valor.
* `.idxmax()` / `.idxmin()`: Onde (índice) estão esses valores.

In [ ]:
# Exemplo .nunique()
# Quantos artistas diferentes foram ouvidos?
num_artistas_unicos = df_spotify['artist_name'].nunique()
print(f"Número de artistas únicos: {num_artistas_unicos}")

In [ ]:
# Exemplo .unique()
# Quais álbuns únicos aparecem nas primeiras 20 músicas?
# (No nosso exemplo, usaremos head(11) pois só temos 11 linhas)
albuns_unicos_primeiros = df_spotify['album_name'].head(11).unique()
print("Álbuns únicos nas primeiras 11 linhas:")
print(albuns_unicos_primeiros)

In [ ]:
# Exemplo .max()
# Qual a maior duração de música (ms)?
max_duracao = df_spotify['duration_ms'].max()
print(f"Maior duração (ms): {max_duracao}")

In [ ]:
# Exemplo .min()
# Qual a menor duração de música (ms)?
min_duracao = df_spotify['duration_ms'].min()
print(f"Menor duração (ms): {min_duracao}")

### ✍️ Exercícios - Estrutura e Métricas

**Exercício 3.1:** Use o método `.head()` para exibir as primeiras 7 linhas do DataFrame.

**Exercício 3.2:** Use o método `.tail()` para exibir as 4 últimas linhas do DataFrame.

**Exercício 3.3:** Use o atributo `.shape` para descobrir e imprimir o número de linhas e colunas.

**Exercício 3.4:** Use o método `.nunique()` para descobrir quantos artistas diferentes existem.

**Exercício 3.5 (Extra):** Use `.info()` e `.describe()` para obter mais informações.

<details>
<summary>Clique aqui para ver a solução</summary>

```python
# Solução 3.1
print("--- Exercício 3.1: .head(7) ---")
display(df_spotify.head(7))

# Solução 3.2
print("\n--- Exercício 3.2: .tail(4) ---")
display(df_spotify.tail(4))

# Solução 3.3
print("\n--- Exercício 3.3: .shape ---")
print(f"Dimensões (linhas, colunas): {df_spotify.shape}")

# Solução 3.4
print("\n--- Exercício 3.4: .nunique() ---")
num_artistas = df_spotify.nunique()
print(f"Número de artistas únicos: {num_artistas}")

# Solução 3.5
print("\n--- Exercício 3.5: .info() ---")
df_spotify.info()

print("\n--- Exercício 3.5: .describe() ---")
display(df_spotify.describe())

In [ ]:
df_spotify.nunique()

---

## 6. SELEÇÕES (Slicing e Filtering)

### Seleção de Colunas
* `df['nome_coluna']`: Seleciona uma única coluna (retorna uma *Series*).
* `df[['coluna1', 'coluna2']]`: Seleciona múltiplas colunas (retorna um *DataFrame*).

In [ ]:
# Exemplo: Seleção de uma única coluna
# Selecionando a coluna 'track_name'
nomes = df_spotify['track_name']
print("--- Coluna Única ('track_name') ---")
display(nomes)

In [ ]:
# Exemplo: Seleção de múltiplas colunas
# Selecionando as colunas 'artist_name' e 'album_name'
artista_album = df_spotify[['artist_name', 'album_name']]
print("\n--- Múltiplas Colunas ('artist_name', 'album_name') ---")
display(artista_album)

### Seleção de Linhas (.loc[] e .iloc[])
Existem duas formas principais de selecionar linhas:

* `.loc[]`: Seleciona pelo **rótulo (label)** do índice.
* `.iloc[]`: Seleciona pela **posição numérica** (inteiro).

Por padrão, o rótulo do índice é igual à sua posição (0, 1, 2, ...).

#### .loc[] (Seleção por Rótulo)
* `df.loc[rotulo_unico]`
* `df.loc[[rotulo1, rotulo2]]`
* `df.loc['inicio':'fim']` (Slice por rótulo **INCLUI** o valor final)

#### .iloc[] (Seleção por Posição)
* `df.iloc[posicao_unica]` (ex: `0` para a primeira linha)
* `df.iloc[[pos1, pos2]]`
* `df.iloc[inicio:fim]` (Slice por posição **EXCLUI** o valor final, como no Python)

In [ ]:
# Exemplo .loc[]
# Seleciona a linha com o rótulo de índice 3
print("--- .loc[3] ---")
display(df_spotify.loc[3])

# Seleciona as linhas com os rótulos 5, 8 e 10
print("\n--- .loc[[5, 8, 10]] ---")
display(df_spotify.loc[[5, 8, 10]])

# Seleciona as linhas com rótulos de 3 até 5 (INCLUINDO a 5)
print("\n--- .loc[3:5] (Inclusivo) ---")
display(df_spotify.loc[3:5])

In [ ]:
# Exemplo .iloc[]
# Seleciona a linha na posição 3 (que é a quarta linha, 0-indexada)
print("--- .iloc[3] ---")
display(df_spotify.iloc[3])

# Seleciona as linhas nas posições 5, 8 e 10
print("\n--- .iloc[[5, 8, 10]] ---")
display(df_spotify.iloc[[5, 8, 10]])

# Seleciona as linhas das posições 3 até 5 (EXCLUINDO a 5)
print("\n--- .iloc[3:5] (Exclusivo) ---")
display(df_spotify.iloc[3:5])

### Seleção Combinada (Linhas e Colunas)
Podemos selecionar linhas e colunas ao mesmo tempo, usando `[linhas, colunas]`:

* `.loc[]` usa **RÓTULOS** para linhas e **NOMES** para colunas.
    * `df.loc[selecao_linhas_ROTULO, selecao_colunas_NOME]`
* `.iloc[]` usa **POSIÇÕES** numéricas para linhas e colunas.
    * `df.iloc[selecao_linhas_POSICAO, selecao_colunas_POSICAO]`

In [ ]:
# Exemplos usando .iloc[]

# Coluna única (pos 3) e linha única (pos 5)
artista_pos_5 = df_spotify.iloc[5, 3] #
print(f"Valor na linha 5, coluna 3: {artista_pos_5}\n")

# Slice de Linhas (pos 2 a 4), Lista de Colunas (pos 2 e 4)
linhas_2a4_cols_pos = df_spotify.iloc[2:5, [2, 4]] #
print("--- .iloc[2:5, [2, 4]] ---")
display(linhas_2a4_cols_pos)

# Lista de Linhas (pos 0 e 10), Slice de Colunas (pos 3 e 4)
linhas_0_10_cols_pos = df_spotify.iloc[[0, 10], 3:5] #
print("\n--- .iloc[[0, 10], 3:5] ---")
display(linhas_0_10_cols_pos)

# Todas as Linhas (:), Lista de Colunas (pos 0 e 2)
linhas_todas_cols_pos = df_spotify.iloc[:, [0, 2]] #
print("\n--- .iloc[:, [0, 2]] ---")
display(linhas_todas_cols_pos.head())

### Localizando Valores Extremos
Para saber *onde* está o maior ou menor valor, usamos:

* `.idxmax()`: Retorna o **rótulo do índice** onde o maior valor ocorre.
* `.idxmin()`: Retorna o **rótulo do índice** onde o menor valor ocorre.

In [ ]:
# Exemplo: Encontrar a música mais longa

# 1. Encontrar o RÓTULO (índice) da música com maior 'duration_ms'
indice_mais_longa = df_spotify['duration_ms'].idxmax()
print(f"Índice (rótulo) da música mais longa: {indice_mais_longa}")

# 2. Usar .loc[] ou .iloc[] para buscar a linha inteira
# (Neste caso, .loc[indice] é mais seguro, pois idxmax retorna o rótulo)
musica_mais_longa = df_spotify.loc[indice_mais_longa]
print("\nDados da música mais longa:")
display(musica_mais_longa)

### Seleção Condicional (Filtros)
Consiste em filtrar linhas que atendem a critérios lógicos (filtros).

1.  Cria-se uma "máscara booleana" (uma Series de True/False).
    * Ex: `df_spotify['artist_name'] == 'Eminem'`
2.  Passa-se essa máscara para o DataFrame:
    * `df[mascara]`

Para múltiplas condições, use `&` (E) ou `|` (OU), com parênteses:
`df[(condicao1) & (condicao2)]`

In [ ]:
# Exemplo: Condição Única
# Filtrando Músicas do artista 'Clairo'
df_clairo = df_spotify[df_spotify['artist_name'] == 'Clairo']
print("--- Músicas da 'Clairo' ---")
display(df_clairo)

In [ ]:
# Exemplo: Múltiplas Condições (& = E)
# Filtrando Músicas do 'Radiohead' E com duração > 180000 ms

df_readiohead_longas = df_spotify[
    (df_spotify['artist_name'] == 'Radiohead') &
    (df_spotify['duration_ms'] > 180000)
]
print("\n--- Músicas do 'Radiohead' > 180000 ms ---")
display(df_readiohead_longas)

In [ ]:
# Exemplo: Múltiplas Condições com variáveis (mais legível)

# 1. Criar a condição para o artista
condicao_artista = df_spotify['artist_name'] == 'Clairo'

# 2. Criar a condição para a duração
condicao_duracao = df_spotify['duration_ms'] < 180000

# 3. Aplicar ambas as condições (combinadas com &)
df_clairo_curtas = df_spotify[condicao_artista & condicao_duracao]

# 4. Mostrando o Resultado
print("\n--- Músicas do 'Clairo' < 195000 ms ---")
display(df_clairo_curtas)

### ✍️ Exercícios - Seleções

**Exercício 4.1 (Seleção de Colunas):**

* Selecione apenas as entradas da coluna 'track_name'.

* Selecione apenas as entradas das colunas 'artist_name' e 'album_name'.
> **Dica:** Para selecionar múltiplas colunas (item 'b'), você precisa passar uma lista de colunas dentro dos colchetes: `df[['col1', 'col2']]`.

**Exercício 4.2 (Seleção de Linhas):**

* Selecione e mostre a linha completa na **posição** 2000 usando `.iloc`.

* Selecione e mostre as linhas com **rótulos** de índice 100 a 104 (inclusive) usando `.loc`.
> **Dica:** Lembre-se que `.iloc[]` usa a posição (inteiro) e `.loc[]` usa o rótulo. O slice com `.loc[inicio:fim]` é inclusivo (inclui o fim).

**Exercício 4.3 (Seleção Condicional):**

* Crie um DataFrame `df_coldplay` contendo apenas as músicas do artista 'Coldplay'.

* Crie um DataFrame `df_igor` contendo músicas do artista 'Tyler, The Creator' e que façam parte do álbum 'IGOR'.
> **Dica:** Para 'b', lembre-se de combinar as condições lógicas com o operador `&` e de envolver cada condição em parênteses: `(cond1) & (cond2)`.

<details>
<summary>Clique aqui para ver a solução</summary>

```python
# Solução 4.1a
print("--- Exercício 4.1a: Coluna 'track_name' ---")
display(df_spotify['track_name'])

# Solução 4.1b
print("\n--- Exercício 4.1b: Colunas 'artist_name' e 'album_name' ---")
display(df_spotify[['artist_name', 'album_name']])

# Solução 4.2a
print("\n--- Exercício 4.2a: Linha na posição 2000 (.iloc[2000]) ---")
# (Nota: Este comando pode dar erro se o seu DataFrame tiver menos de 2001 linhas)
display(df_spotify.iloc[2000])

# Solução 4.2b
print("\n--- Exercício 4.2b: Linhas com rótulos 100 a 104 (.loc[100:104]) ---")
# (Nota: Este comando pode dar erro se os rótulos 100 a 104 não existirem)
display(df_spotify.loc[100:104])

# Solução 4.3a
print("\n--- Exercício 4.3a: Músicas do 'Coldplay' ---")
df_coldplay = df_spotify[df_spotify['artist_name'] == 'Coldplay']
display(df_coldplay)

# Solução 4.3b
print("\n--- Exercício 4.3b: Músicas do 'Tyler, The Creator' no álbum 'IGOR' ---")
df_igor = df_spotify[
    (df_spotify['artist_name'] == 'Tyler, The Creator') &
    (df_spotify['album_name'] == 'IGOR')
]
display(df_igor)

In [ ]:
# Solução 4.1a
print("--- Exercício 4.1a: Coluna 'track_name' ---")
display(df_spotify['track_name'])

# Solução 4.1b
print("\n--- Exercício 4.1b: Colunas 'artist_name' e 'album_name' ---")
display(df_spotify[['artist_name', 'album_name']])

# Solução 4.2a
print("\n--- Exercício 4.2a: Linha na posição 2000 (.iloc[2000]) ---")
# (Nota: Este comando pode dar erro se o seu DataFrame tiver menos de 2001 linhas)
display(df_spotify.iloc[2000])

# Solução 4.2b
print("\n--- Exercício 4.2b: Linhas com rótulos 100 a 104 (.loc[100:104]) ---")
# (Nota: Este comando pode dar erro se os rótulos 100 a 104 não existirem)
display(df_spotify.loc[100:104])

# Solução 4.3a
print("\n--- Exercício 4.3a: Músicas do 'Coldplay' ---")
df_coldplay = df_spotify[df_spotify['artist_name'] == 'Coldplay']
display(df_coldplay)

# Solução 4.3b
print("\n--- Exercício 4.3b: Músicas do 'Tyler, The Creator' no álbum 'IGOR' ---")
df_igor = df_spotify[
    (df_spotify['artist_name'] == 'Tyler, The Creator') &
    (df_spotify['album_name'] == 'IGOR')
]
display(df_igor)

--- Exercício 4.1a: Coluna 'track_name' ---

0                                   Silence
1               Mask Off - Marshmello Remix
2                                    Summer
3         Chasing Colors (feat. Noah Cyrus)
4                                   Know Me
                        ...
211888                          Cementality
211889                          Cementality
211890                       A Lizard State
211891                          Will I Come
211892                            Ocean Bed
Name: track_name, Length: 211893, dtype: object

--- Exercício 4.1b: Colunas 'artist_name' e 'album_name' ---

       artist_name                         album_name
0       Marshmello                            Silence
1           Future                           Mask Off
2       Marshmello                            Joytime
3       Marshmello  Chasing Colors (feat. Noah Cyrus)
4       Marshmello                            Joytime
...            ...                                ...
211888  King Krule            6 Feet Beneath the Moon
211889  King Krule            6 Feet Beneath the Moon
211890  King Krule            6 Feet Beneath the Moon
211891  King Krule            6 Feet Beneath the Moon
211892  King Krule            6 Feet Beneath the Moon

[211893 rows x 2 columns]

--- Exercício 4.2a: Linha na posição 2000 (.iloc[2000]) ---

timestamp       2019-11-13 22:42:38+00:00
duration_ms                          2397
track_name                          Farsa
artist_name                          UCLÃ
album_name                          Farsa
artist_track                 UCLÃ - Farsa
Name: 2000, dtype: object

--- Exercício 4.2b: Linhas com rótulos 100 a 104 (.loc[100:104]) ---

,timestamp,duration_ms,track_name,artist_name,album_name,artist_track
100,2017-11-15 12:45:09+00:00,212627,Faded,Alan Walker,Faded,Alan Walker - Faded
101,2017-11-15 12:48:35+00:00,206197,Know Me,Marshmello,Joytime,Marshmello - Know Me
102,2017-11-15 12:51:50+00:00,195200,Chasing Colors (feat. Noah Cyrus),Marshmello,Chasing Colors (feat. Noah Cyrus),Marshmello - Chasing Colors (feat. Noah Cyrus)
103,2017-11-15 12:55:43+00:00,233239,Summer,Marshmello,Joytime,Marshmello - Summer
104,2017-11-15 12:58:42+00:00,179155,Moving On,Marshmello,Moving On,Marshmello - Moving On

--- Exercício 4.3a: Músicas do 'Coldplay' ---

,timestamp,duration_ms,track_name,artist_name,album_name,artist_track
6067,2019-12-06 16:43:29+00:00,609,Hymn for the Weekend,Coldplay,A Head Full of Dreams,Coldplay - Hymn for the Weekend
15452,2020-12-12 21:27:15+00:00,309600,The Scientist,Coldplay,A Rush of Blood to the Head,Coldplay - The Scientist
15549,2020-12-14 02:59:19+00:00,258267,Hymn for the Weekend,Coldplay,A Head Full of Dreams,Coldplay - Hymn for the Weekend
15581,2020-12-14 17:30:22+00:00,295533,Fix You,Coldplay,X&Y,Coldplay - Fix You
15596,2020-12-14 20:34:26+00:00,1097,Clocks,Coldplay,A Rush of Blood to the Head,Coldplay - Clocks
...,...,...,...,...,...,...
209759,2025-09-17 01:15:34+00:00,256466,High Speed,Coldplay,Parachutes,Coldplay - High Speed
209760,2025-09-17 01:19:43+00:00,249400,We Never Change,Coldplay,Parachutes,Coldplay - We Never Change
209761,2025-09-17 01:26:59+00:00,436440,Everything's Not Lost - Includes Hidden Track ...,Coldplay,Parachutes,Coldplay - Everything's Not Lost - Includes Hi...
209762,2025-09-17 01:31:46+00:00,285345,A Message,Coldplay,X&Y,Coldplay - A Message
211503,2025-09-29 09:48:35+00:00,226680,In My Place,Coldplay,A Rush of Blood to the Head,Coldplay - In My Place

--- Exercício 4.3b: Músicas do 'Tyler, The Creator' no álbum 'IGOR' ---

,timestamp,duration_ms,track_name,artist_name,album_name,artist_track
14872,2020-12-07 13:57:08+00:00,190067,EARFQUAKE,"Tyler, The Creator",IGOR,"Tyler, The Creator - EARFQUAKE"
16022,2020-12-18 23:46:13+00:00,190067,EARFQUAKE,"Tyler, The Creator",IGOR,"Tyler, The Creator - EARFQUAKE"
16086,2020-12-19 02:45:18+00:00,190067,EARFQUAKE,"Tyler, The Creator",IGOR,"Tyler, The Creator - EARFQUAKE"
16482,2020-12-21 18:14:35+00:00,190067,EARFQUAKE,"Tyler, The Creator",IGOR,"Tyler, The Creator - EARFQUAKE"
16724,2020-12-23 18:10:12+00:00,190067,EARFQUAKE,"Tyler, The Creator",IGOR,"Tyler, The Creator - EARFQUAKE"
...,...,...,...,...,...,...
205359,2025-08-10 17:17:42+00:00,235,I DON'T LOVE YOU ANYMORE,"Tyler, The Creator",IGOR,"Tyler, The Creator - I DON'T LOVE YOU ANYMORE"
205705,2025-08-15 02:13:01+00:00,212013,I THINK,"Tyler, The Creator",IGOR,"Tyler, The Creator - I THINK"
206820,2025-08-24 18:40:35+00:00,210253,A BOY IS A GUN*,"Tyler, The Creator",IGOR,"Tyler, The Creator - A BOY IS A GUN*"
211788,2025-10-01 16:11:41+00:00,212013,I THINK,"Tyler, The Creator",IGOR,"Tyler, The Creator - I THINK"
211809,2025-10-01 17:26:57+00:00,265480,ARE WE STILL FRIENDS?,"Tyler, The Creator",IGOR,"Tyler, The Creator - ARE WE STILL FRIENDS?"

---

## 7. COLUNAS: CRIANDO & EXCLUINDO

### Criação de Novas Colunas
Usamos para armazenar resultados de cálculos ou combinar informações.

A sintaxe é simples: `df['NomeNovaColuna'] = expressao`

In [ ]:
# Exemplo 1: Criar coluna 'duration_seconds' (Cálculo)
# Dividir 'duration_ms' por 1000
df_spotify['duration_seconds'] = df_spotify['duration_ms'] / 1000

print("--- DataFrame com 'duration_seconds' ---")
display(df_spotify.head())

--- DataFrame com 'duration_seconds' ---

,timestamp,duration_ms,track_name,artist_name,album_name,artist_track,duration_seconds
0,2017-11-04 21:53:34+00:00,48330,Silence,Marshmello,Silence,Marshmello - Silence,48.33
1,2017-11-04 21:53:46+00:00,11190,Mask Off - Marshmello Remix,Future,Mask Off,Future - Mask Off - Marshmello Remix,11.19
2,2017-11-04 21:53:53+00:00,5970,Summer,Marshmello,Joytime,Marshmello - Summer,5.97
3,2017-11-04 21:54:23+00:00,28640,Chasing Colors (feat. Noah Cyrus),Marshmello,Chasing Colors (feat. Noah Cyrus),Marshmello - Chasing Colors (feat. Noah Cyrus),28.64
4,2017-11-04 21:54:57+00:00,31050,Know Me,Marshmello,Joytime,Marshmello - Know Me,31.05

In [ ]:
# Exemplo 2: Criar coluna 'artist_track' (Concatenação)
# Juntar 'artist_name' e 'track_name'
df_spotify['artist_track'] = df_spotify['artist_name'] + ' - ' + df_spotify['track_name']

print("\n--- DataFrame com 'artist_track' ---")
display(df_spotify.head())

--- DataFrame com 'artist_track' ---

,timestamp,duration_ms,track_name,artist_name,album_name,artist_track,duration_seconds
0,2017-11-04 21:53:34+00:00,48330,Silence,Marshmello,Silence,Marshmello - Silence,48.33
1,2017-11-04 21:53:46+00:00,11190,Mask Off - Marshmello Remix,Future,Mask Off,Future - Mask Off - Marshmello Remix,11.19
2,2017-11-04 21:53:53+00:00,5970,Summer,Marshmello,Joytime,Marshmello - Summer,5.97
3,2017-11-04 21:54:23+00:00,28640,Chasing Colors (feat. Noah Cyrus),Marshmello,Chasing Colors (feat. Noah Cyrus),Marshmello - Chasing Colors (feat. Noah Cyrus),28.64
4,2017-11-04 21:54:57+00:00,31050,Know Me,Marshmello,Joytime,Marshmello - Know Me,31.05

### Removendo Colunas e Linhas (.drop())
O método `.drop()` serve para remover linhas ou colunas.

Parâmetros principais:
* `labels`: Rótulo(s) a remover (nome da coluna ou rótulo do índice).
* `axis`: Define o eixo.
    * `axis=0` (padrão) = remove **LINHAS**.
    * `axis=1` = remove **COLUNAS**.
* `inplace`:
    * `False` (padrão): Retorna uma **cópia** do DataFrame com a remoção. O original não muda.
    * `True`: Modifica o DataFrame **original** e não retorna nada.

In [ ]:
# Exemplo: Remover LINHAS por rótulo

# Vamos criar uma cópia para não afetar o df original nos exemplos
df_exemplo_drop = df_spotify.copy()

# Exemplo 1a: Remover uma única linha (rótulo 3) e criar um NOVO DataFrame
print("--- DataFrame Original (head) ---")
display(df_exemplo_drop.head())

df_sem_linha_3 = df_exemplo_drop.drop(3) # axis=0 é o padrão
print("\n--- Cópia após remover linha com rótulo 3 ---")
display(df_sem_linha_3.head())

# Exemplo 1b: Remover múltiplas linhas (rótulos 0 e 2)
df_sem_linhas_0_2 = df_exemplo_drop.drop([0, 2])
print("\n--- Cópia após remover linhas 0 e 2 ---")
display(df_sem_linhas_0_2.head())

# Exemplo 1c: Remover linha (rótulo 4) DIRETAMENTE no DataFrame (inplace=True)
df_exemplo_drop.drop(4, inplace=True)
print("\n--- DataFrame original após .drop(4, inplace=True) ---")
display(df_exemplo_drop.head())

In [ ]:
# Exemplo: Remover COLUNAS por rótulo

# Vamos usar uma cópia limpa
df_exemplo_drop_cols = df_spotify.copy()
print("--- DataFrame Original (head) ---")
display(df_exemplo_drop_cols.head())

# Exemplo 2b: Remover múltiplas colunas e criar um NOVO DataFrame
colunas_remover = ['album_name', 'artist_track']
df_reduzido = df_exemplo_drop_cols.drop(colunas_remover, axis=1)
# Alternativa: df_reduzido = df_exemplo_drop_cols.drop(columns=colunas_remover)

print(f"\n--- Cópia após remover {colunas_remover} ---")
display(df_reduzido.head())

# Exemplo 2c: Remover uma coluna ('duration_seconds') DIRETAMENTE no original
df_exemplo_drop_cols.drop('duration_seconds', axis=1, inplace=True)
print("\n--- DataFrame original após .drop('duration_seconds', inplace=True) ---")
display(df_exemplo_drop_cols.head())

### Renomeando Colunas (.rename())
Usamos o `.rename()` para alterar nomes de colunas (ou índices).
Ele usa um dicionário para mapear nomes antigos para novos: `{'nome_antigo': 'nome_novo'}`.

Sintaxe: `df.rename(columns=meu_dicionario)`.

Por padrão, `.rename()` retorna uma **cópia**. Use `inplace=True` para modificar o original.

In [ ]:
# Exemplo: Renomear colunas (retornando uma cópia)

# Define o mapa de renomeação
mapa_nomes = {
    'track_name': 'musica',
    'artist_name': 'artista'
}

print("Colunas Originais:", df_spotify.columns.to_list())

# Renomeia as colunas e armazena em um NOVO DataFrame
df_spotify_renomeado = df_spotify.rename(columns=mapa_nomes)

# Mostra o resultado do NOVO DataFrame
print("Colunas do Novo DF:", df_spotify_renomeado.columns.to_list())

# Mostra que o ORIGINAL não mudou
print("Colunas Originais (não mudou):", df_spotify.columns.to_list())

In [ ]:
# Exemplo: Renomear colunas (inplace=True)

# Vamos usar uma cópia para este exemplo
df_spotify_copy = df_spotify.copy()
print("Colunas Originais (Cópia):", df_spotify_copy.columns.to_list())

# 1. Definir o mapa
mapa_nomes_inplace = {
    'album_name': 'album',
    'duration_ms': 'duracao_ms' # Renomeei 'duracao' para 'duracao_ms' para evitar confusão com o exercício
}

# 2. Renomear inplace (modifica df_spotify_copy diretamente)
df_spotify_copy.rename(columns=mapa_nomes_inplace, inplace=True)

# 3. Verificar as colunas (agora modificada)
print("Colunas Modificadas (Inplace):", df_spotify_copy.columns.to_list())

### Salvando os Resultados (.to_csv())
Após as modificações, podemos salvar o DataFrame em um novo arquivo (ex: CSV).

`index=False` é usado para não salvar a coluna de índice do Pandas no arquivo.

In [ ]:
# Exemplo: Salvando o DataFrame

# Ajuste o caminho conforme necessário
caminho_saida = 'spotify_analisado_dia1.csv' #
# Ex: '/content/drive/MyDrive/spotify_analisado_dia1.csv'

try:
    # Salvar sem a coluna de índice do Pandas
    df_spotify.to_csv(caminho_saida, index=False) #
    print(f"\nDataFrame salvo com sucesso em '{caminho_saida}'!") #
    # (Verifique o ícone de pasta na barra lateral)
except Exception as e:
    print(f"\nErro ao salvar o arquivo: {e}") #

### ✍️ Exercícios - Criando e Excluindo Colunas

**Exercício 5.1 (Criação de Colunas):**

* Crie a coluna `duration_seconds` dividindo `duration_ms` por 1000.

* Crie a coluna `artist_track` concatenando `artist_name` - `track_name`.
> **Dica:** A sintaxe para criar colunas é `df['nova_coluna'] = ...`. Você pode somar colunas de string para concatená-las.

**Exercício 5.2 (Renomeando):**
* Crie um **novo** DataFrame `df_spotify_pt` renomeando as colunas `track_name` para `nome_musica` e `artist_name` para `nome_artista`.
> **Dica:** Use `.rename(columns={'nome_antigo': 'nome_novo', ...})`

**Exercício 5.3 (Removendo colunas):**

* Crie um **novo** DataFrame `df_spotify_sem_album` removendo a coluna `album_name` do `df_spotify`.

* Remova a coluna `duration_ms` do DataFrame `df_spotify` original, usando `inplace=True`. (Faça isso em uma cópia).
> **Dica:** Para remover colunas, use `.drop('nome_coluna', axis=1)`. Lembre-se do `inplace=True` para o item 'b'.

<details>
<summary>Clique aqui para ver a solução</summary>

```python
# Solução 5.1
print("--- Exercício 5.1: Criando colunas ---")
df_spotify['duration_seconds'] = df_spotify['duration_ms'] / 1000
df_spotify['artist_track'] = df_spotify['artist_name'] + ' - ' + df_spotify['track_name']
display(df_spotify.head())

# Solução 5.2
print("\n--- Exercício 5.2: Renomeando para df_spotify_pt ---")
mapa_pt = {
    'track_name': 'nome_musica',
    'artist_name': 'nome_artista'
}
df_spotify_pt = df_spotify.rename(columns=mapa_pt)
display(df_spotify_pt.head())

# Solução 5.3a
print("\n--- Exercício 5.3a: Removendo 'album_name' (Cópia) ---")
df_spotify_sem_album = df_spotify.drop('album_name', axis=1)
display(df_spotify_sem_album.head())

# Solução 5.3b
print("\n--- Exercício 5.3b: Removendo 'duration_ms' (Inplace) ---")
# Vamos usar uma cópia para não estragar o original
df_spotify_copy_ex3 = df_spotify.copy()
print("Colunas ANTES:", df_spotify_copy_ex3.columns.to_list())
df_spotify_copy_ex3.drop('duration_ms', axis=1, inplace=True)
print("Colunas DEPOIS:", df_spotify_copy_ex3.columns.to_list())
display(df_spotify_copy_ex3.head())

In [ ]:
# Solução 5.1
print("--- Exercício 5.1: Criando colunas ---")
df_spotify['duration_seconds'] = df_spotify['duration_ms'] / 1000
df_spotify['artist_track'] = df_spotify['artist_name'] + ' - ' + df_spotify['track_name']
display(df_spotify.head())

# Solução 5.2
print("\n--- Exercício 5.2: Renomeando para df_spotify_pt ---")
mapa_pt = {
    'track_name': 'nome_musica',
    'artist_name': 'nome_artista'
}
df_spotify_pt = df_spotify.rename(columns=mapa_pt)
display(df_spotify_pt.head())

# Solução 5.3a
print("\n--- Exercício 5.3a: Removendo 'album_name' (Cópia) ---")
df_spotify_sem_album = df_spotify.drop('album_name', axis=1)
display(df_spotify_sem_album.head())

# Solução 5.3b
print("\n--- Exercício 5.3b: Removendo 'duration_ms' (Inplace) ---")
# Vamos usar uma cópia para não estragar o original
df_spotify_copy_ex3 = df_spotify.copy()
print("Colunas ANTES:", df_spotify_copy_ex3.columns.to_list())
df_spotify_copy_ex3.drop('duration_ms', axis=1, inplace=True)
#df_spotify_copy_ex3 = df_spotify_copy_ex3.drop('duration_ms', axis=1)
print("Colunas DEPOIS:", df_spotify_copy_ex3.columns.to_list())
display(df_spotify_copy_ex3.head())

--- Exercício 5.1: Criando colunas ---

,timestamp,duration_ms,track_name,artist_name,album_name,artist_track,duration_seconds
0,2017-11-04 21:53:34+00:00,48330,Silence,Marshmello,Silence,Marshmello - Silence,48.33
1,2017-11-04 21:53:46+00:00,11190,Mask Off - Marshmello Remix,Future,Mask Off,Future - Mask Off - Marshmello Remix,11.19
2,2017-11-04 21:53:53+00:00,5970,Summer,Marshmello,Joytime,Marshmello - Summer,5.97
3,2017-11-04 21:54:23+00:00,28640,Chasing Colors (feat. Noah Cyrus),Marshmello,Chasing Colors (feat. Noah Cyrus),Marshmello - Chasing Colors (feat. Noah Cyrus),28.64
4,2017-11-04 21:54:57+00:00,31050,Know Me,Marshmello,Joytime,Marshmello - Know Me,31.05

--- Exercício 5.2: Renomeando para df_spotify_pt ---

,timestamp,duration_ms,nome_musica,nome_artista,album_name,artist_track,duration_seconds
0,2017-11-04 21:53:34+00:00,48330,Silence,Marshmello,Silence,Marshmello - Silence,48.33
1,2017-11-04 21:53:46+00:00,11190,Mask Off - Marshmello Remix,Future,Mask Off,Future - Mask Off - Marshmello Remix,11.19
2,2017-11-04 21:53:53+00:00,5970,Summer,Marshmello,Joytime,Marshmello - Summer,5.97
3,2017-11-04 21:54:23+00:00,28640,Chasing Colors (feat. Noah Cyrus),Marshmello,Chasing Colors (feat. Noah Cyrus),Marshmello - Chasing Colors (feat. Noah Cyrus),28.64
4,2017-11-04 21:54:57+00:00,31050,Know Me,Marshmello,Joytime,Marshmello - Know Me,31.05

--- Exercício 5.3a: Removendo 'album_name' (Cópia) ---

,timestamp,duration_ms,track_name,artist_name,artist_track,duration_seconds
0,2017-11-04 21:53:34+00:00,48330,Silence,Marshmello,Marshmello - Silence,48.33
1,2017-11-04 21:53:46+00:00,11190,Mask Off - Marshmello Remix,Future,Future - Mask Off - Marshmello Remix,11.19
2,2017-11-04 21:53:53+00:00,5970,Summer,Marshmello,Marshmello - Summer,5.97
3,2017-11-04 21:54:23+00:00,28640,Chasing Colors (feat. Noah Cyrus),Marshmello,Marshmello - Chasing Colors (feat. Noah Cyrus),28.64
4,2017-11-04 21:54:57+00:00,31050,Know Me,Marshmello,Marshmello - Know Me,31.05

--- Exercício 5.3b: Removendo 'duration_ms' (Inplace) ---
Colunas ANTES: ['timestamp', 'duration_ms', 'track_name', 'artist_name', 'album_name', 'artist_track', 'duration_seconds']
Colunas DEPOIS: ['timestamp', 'track_name', 'artist_name', 'album_name', 'artist_track', 'duration_seconds']

,timestamp,track_name,artist_name,album_name,artist_track,duration_seconds
0,2017-11-04 21:53:34+00:00,Silence,Marshmello,Silence,Marshmello - Silence,48.33
1,2017-11-04 21:53:46+00:00,Mask Off - Marshmello Remix,Future,Mask Off,Future - Mask Off - Marshmello Remix,11.19
2,2017-11-04 21:53:53+00:00,Summer,Marshmello,Joytime,Marshmello - Summer,5.97
3,2017-11-04 21:54:23+00:00,Chasing Colors (feat. Noah Cyrus),Marshmello,Chasing Colors (feat. Noah Cyrus),Marshmello - Chasing Colors (feat. Noah Cyrus),28.64
4,2017-11-04 21:54:57+00:00,Know Me,Marshmello,Joytime,Marshmello - Know Me,31.05